token: V2Npu26Zgx1cuMWUPFVY
baseURL: http://10.211.62.41:8081/api/v4

#定时任务配置
#*  *  *  *  *  *
#┬ ┬ ┬ ┬ ┬ ┬
#│ │ │ │ │ │ 
#│ │ │ │ │ └ day of week (0 - 7) (0 or 7 is Sun)
#│ │ │ │ └───── month (1 - 12)
#│ │ │ └────────── day of month (1 - 31)
#│ │ └─────────────── hour (0 - 23)
#│ └──────────────────── minute (0 - 59)
#└───────────────────────── second (0 - 59, OPTIONAL)
#每分钟的第30秒触发： '30 * * * * *'
#每小时的1分30秒触发 ：'30 1 * * * *'
#每天的凌晨1点1分30秒触发 ：'30 1 1 * * *'
#每月的1日1点1分30秒触发 ：'30 1 1 1 * *'
#2016年的1月1日1点1分30秒触发 ：'30 1 1 1 2016 *'
#每周1的1点1分30秒触发 ：'30 1 1 * * 1'
checkSchedule: 30 30 10 * * *

# 检测列表
checkList: 
  -
    id: 1451
    name: admin-api
    subtitle: 欣和食与家后台管理系统-服务端（食谱）
    ownerPhone: 18516236270
  -
    id: 1450
    name: wechat-mini-program-api
    subtitle: 欣和食与家微信小程序-服务端（食谱）
    ownerPhone: 18516236270
  -
    id: 1449
    name: admin-web
    subtitle: 欣和食与家后台管理系统-前端（食谱）
    ownerPhone: 18516236270
  -
    id: 1448
    name: wechat-mini-program
    subtitle: 欣和食与家微信小程序-前端（食谱）
    ownerPhone: 18516236270

# 检测正则
regex:
  # master
  master: ^master$
  # release
  # 预发布时间：格式为 2019-05-20，例如：分支名 release_2019-05-20
  release: ^release_\d{4}-\d{2}-\d{2}$
  # feature
  # 功能点名称：格式为小写连字符 -，例如：用户详情 feature_user-details
  feature: ^feature_([a-z]{1,}-){0,}[a-z]{1,}$
  # hotfix
  # bug号：为修复对应的 Jira   Bug编号。
  hotfix: ^hotfix_\w{1,}-\w{1,}$
  # dev
  # 图像项目特殊分支 dev_integrate
  dev: ^dev_integrate$
  # tag
  # vx.x.x
  tag: ^v(\d{1,}\.){1,}\d$