token: V2Npu26Zgx1cuMWUPFVY
baseURL: http://10.211.62.41:8081/api/v4

#定时任务配置
#*  *  *  *  *  *
#┬ ┬ ┬ ┬ ┬ ┬
#│ │ │ │ │ │ 
#│ │ │ │ │ └ day of week (0 - 7) (0 or 7 is Sun)
#│ │ │ │ └───── month (1 - 12)
#│ │ │ └────────── day of month (1 - 31)
#│ │ └─────────────── hour (0 - 23)
#│ └──────────────────── minute (0 - 59)
#└───────────────────────── second (0 - 59, OPTIONAL)
#每分钟的第30秒触发： '30 * * * * *'
#每小时的1分30秒触发 ：'30 1 * * * *'
#每天的凌晨1点1分30秒触发 ：'30 1 1 * * *'
#每月的1日1点1分30秒触发 ：'30 1 1 1 * *'
#2016年的1月1日1点1分30秒触发 ：'30 1 1 1 2016 *'
#每周1的1点1分30秒触发 ：'30 1 1 * * 1'
checkSchedule: 30 30 10 * * *

# 检测列表
checkList: 
  -
    id: 1451
    name: admin-api
    subtitle: 欣和食与家后台管理系统-服务端（食谱）
    ownerPhone: 18516236270
  -
    id: 1450
    name: wechat-mini-program-api
    subtitle: 欣和食与家微信小程序-服务端（食谱）
    ownerPhone: 18516236270
  -
    id: 1449
    name: admin-web
    subtitle: 欣和食与家后台管理系统-前端（食谱）
    ownerPhone: 18516236270
  -
    id: 1448
    name: wechat-mini-program
    subtitle: 欣和食与家微信小程序-前端（食谱）
    ownerPhone: 18516236270
